name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
#    - uses: bazelbuild/setup-bazelisk@v3 deprecated
    - uses: bazel-contrib/setup-bazel@0.14.0
#    - name: Mount bazel cache  # Optional
#      uses: actions/cache@v4
#      with:
#        path: "~/.cache/bazel"
#        key: bazel
#    - run: (cd hello-world && bazel build //... && echo hi)
    - name: Run Python Script
      run: python check_duplicate_tests.py
